Fix/assessment multi tap
zoe/covid-tracker-react-native pull request #1032
Opened 2020-12-29 15:11 UTC by petermason

# Description

_Description of the feature or fix with link to the issue if existing_

## On what platform have you tested the change?

- [x] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

2020-12-31 11:28 UTC, selvach requested changes
Could you apply the changes onto the current `develop` branch please. Looks like you've got changes in the `yarn.lock` file.

2020-12-31 11:31 UTC, petermason commented
> Could you apply the changes onto the current `develop` branch please. Looks like you've got changes in the `yarn.lock` file.

This will be an issue until we fix versions, however, the build will handle this by run running yarn

2021-01-14 13:12 UTC, bionara approved these changes
Code looks good!

2021-01-14 15:45 UTC, selvach approved these changes

2021-01-14 16:29 UTC, merged