Fix/boot loading
zoe/covid-tracker-react-native pull request #1039
Opened 2020-12-31 15:58 UTC by petermason

# Description

Refactor initial boot with asyncStorage and redux

## On what platform have you tested the change?

- [x] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

2021-01-05 16:17 UTC, the-kenneth commented
Is this ready for review or still a draft @petermason ?

2021-01-14 15:21 UTC, bionara commented on src/features/index.ts
> +export { default as LoginScreen } from './login/LoginScreen';
minor one to make maintenance easy - export LoginScreen explicitly vs as default perhaps

2021-01-14 17:20 UTC, the-kenneth commented on src/core/state/store.ts
> +  middleware: [thunk],
If using persist with redux-toolkit it mentions that a number of actions should be ignored in the middleware (https://redux-toolkit.js.org/usage/usage-guide)

2021-01-14 17:37 UTC, the-kenneth requested changes

2021-01-14 17:37 UTC, the-kenneth commented on src/core/state/store.ts
> +  middleware: [thunk],
If using persist with redux-toolkit it mentions that a number of actions should be ignored in the middleware (https://redux-toolkit.js.org/usage/usage-guide)

2021-01-14 17:37 UTC, the-kenneth commented on src/core/state/store.ts
> +// export default () => {
Is this commented code needed?

2021-01-14 17:37 UTC, the-kenneth commented on src/core/state/user/slice/index.ts
> +  reducers: {
Using redux-toolkit, createReducer and createSlice are wrapped with the immer lib (https://github.com/immerjs/immer) that allows mutable changes to the state to improve readability (immer makes the change immutably for you in the background).  Can we change these to state.whatever = action.payload

2021-01-14 17:37 UTC, the-kenneth commented on src/features/SplashScreen.tsx
> +  setUsername: (username: string) => void;
Can this be defined in the ScreenParamList?

2021-01-14 17:37 UTC, the-kenneth commented on src/features/login/LoginScreen.tsx
> +  setUsername: (username: string) => void;
Can this be defined in the ScreenParamList?

Edit: This has something to do with using connect() ? I dont think it might be needed if using the redux hooks

2021-01-14 17:37 UTC, the-kenneth commented on src/features/login/LoginScreen.tsx
> +export default connect(null, mapDispatchToProps)(LoginScreen);
Can we use the redux hooks (https://react-redux.js.org/api/hooks) instead of wrapping with connect? It makes the code a lot cleaner

2021-01-14 17:37 UTC, the-kenneth commented on src/features/register/RegisterScreen.tsx
> +export default connect(null, mapDispatchToProps)(RegisterScreen);
As mentioned above.

2021-01-14 17:42 UTC, petermason commented on src/features/login/LoginScreen.tsx
> +export default connect(null, mapDispatchToProps)(LoginScreen);
Hooks don't work in class components

2021-01-14 17:42 UTC, petermason commented on src/features/register/RegisterScreen.tsx
> +export default connect(null, mapDispatchToProps)(RegisterScreen);
not a functional component

2021-01-14 17:49 UTC, the-kenneth commented on src/features/login/LoginScreen.tsx
> +export default connect(null, mapDispatchToProps)(LoginScreen);
Sorry yes, I meant we transform them to functional components on the way as its probably better anyway :)

2021-01-15 14:23 UTC, petermason commented on src/features/login/LoginScreen.tsx
> +export default connect(null, mapDispatchToProps)(LoginScreen);
This structure is present if a few files. I think I would like to put these changes into a seperate PR. What do you think?

2021-01-15 15:24 UTC, the-kenneth approved these changes

2021-01-15 16:09 UTC, merged