feat: fetch & store featured content in redux, diaply via FeatureCont…
zoe/covid-tracker-react-native pull request #1041
Opened 2021-01-05 18:08 UTC by snack-0verflow

…entList.tsx

# Description

_Description of the feature or fix with link to the issue if existing_

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

2021-01-07 20:10 UTC, selvach approved these changes

2021-01-07 20:11 UTC, selvach commented
@snack-0verflow Are the changes to es.json purely formatting?

2021-01-08 11:37 UTC, petermason approved these changes

2021-01-08 12:03 UTC, the-kenneth requested changes

2021-01-08 12:03 UTC, the-kenneth commented on src/components/Content/FeaturedContentList.tsx
> +        aspectRatio={1029 / 600}
This should probably be height / width incase the image changes size in the future?

2021-01-08 14:03 UTC, snack-0verflow commented
> @snack-0verflow Are the changes to es.json purely formatting?

Yes

2021-01-08 14:04 UTC, snack-0verflow commented on src/components/Content/FeaturedContentList.tsx
> +        aspectRatio={1029 / 600}
Atm is assuming the content size is the same, as the backend content doesn't have sizes specified

2021-01-08 15:28 UTC, the-kenneth commented on src/components/Content/FeaturedContentList.tsx
> +        aspectRatio={1029 / 600}
Is it not possible to get the sizing dynamically? If its not easy we can leave it for now

2021-01-09 08:15 UTC, selvach commented on src/components/Content/FeaturedContentList.tsx
> +        aspectRatio={1029 / 600}
The aspectRatio was something I introduced in order to get the correctly center the card in the parent container and have the image fill the space. There might be a better way to this which doesn't requite the aspect ratio....

2021-01-11 16:51 UTC, the-kenneth approved these changes

2021-01-11 16:52 UTC, merged