WIP: Vaccines List View
zoe/covid-tracker-react-native pull request #1565
Opened 2021-08-04 18:08 UTC by juliatan

# Description

https://www.notion.so/joinzoe/Vaccine-Logging-List-View-efae05e25ccd4f439070f2f389e5ad96
https://www.figma.com/file/7TEcX7f6rw3Z0WYR4TpX3R/ZOE-COVID-Study-(App)---MASTER?node-id=12017%3A138203

WIP - do not merge

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

[comment]: <> (Please attach screenshots showing the change, if relevant)

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

2021-08-04 18:13 UTC, juliatan commented on src/core/state/vaccines/slice/index.ts
> +export const fetchVaccines = createAsyncThunk<unknown, string>(
I'm not sure why the decision was made to call the API endpoint in the Redux slice, considering the list of vaccines are not then added to the state. Do you guys think I should leave here or move call to the component? 🤔

2021-08-05 11:15 UTC, bionara commented on src/core/state/vaccines/slice/index.ts
> +export const fetchVaccines = createAsyncThunk<unknown, string>(
I think move to the component then it's one less async thunk to worry about in the codebase!

2021-08-05 11:26 UTC, bionara submitted a review, later dismissed
Looks good so far!

2021-08-16 08:55 UTC, aikewoody commented on src/features/vaccines/components/VaccineDoseRow.tsx
> +    return dose.brand ? vaccineBrandDisplayName[dose.brand] : 'Unknown';
Should this be translated?

2021-08-16 08:57 UTC, aikewoody commented on src/features/vaccines/fields/VaccineDoseQuestion.tsx
> +      minDate = new Date('2020-12-08');
Why specifically this date?

2021-08-16 08:57 UTC, aikewoody commented on src/features/vaccines/fields/VaccineDoseQuestion.tsx
> +      minDate = new Date('2020-12-11');
Why specifically these dates?

2021-08-16 08:58 UTC, aikewoody commented on src/features/vaccines/__tests__/VaccineListScreenUpdated.test.tsx
> +});
Loving all the tests you're writing!

2021-08-17 15:25 UTC, bionara commented on src/features/vaccines/components/VaccineDoseRow.tsx
> +    return dose.brand ? vaccineBrandDisplayName[dose.brand] : 'Unknown';
I think this is more to stop a crash on key error, ie return a string: in theory, this should never happen as all doses need brand.

2021-08-17 15:26 UTC, bionara commented on src/features/vaccines/fields/VaccineDoseQuestion.tsx
> +      minDate = new Date('2020-12-11');
these are the "launch dates" for vaccines in those countries: minDate stops vaccines being entered before those dates

2021-08-18 10:26 UTC, bionara commented on src/NavigatorService.ts
> +function push<RouteName extends TScreenName>(routeName: RouteName, params?: TScreenParamList[RouteName]) {
@Aike added the navigation push method to our navigator service. I needed it to be used to “fake” an entry on nav stack as the feature toggle screen for vaccines serves multiple views.

2021-08-18 10:26 UTC, bionara commented on src/core/assessment/AssessmentCoordinator.ts
> +    // FeatureToggle: Use push to add "another" state to nav stack so that its back returns to "itself" (defaults to LIST view)
@Aike using the push here btw

2021-08-18 13:55 UTC, aikewoody commented on src/features/vaccines/components/VaccineDoseRow.tsx
> +    return dose.brand ? vaccineBrandDisplayName[dose.brand] : 'Unknown';
Got it, then the `TODO` can be removed, right?

2021-08-18 13:56 UTC, aikewoody commented on src/features/vaccines/fields/VaccineDoseQuestion.tsx
> +      minDate = new Date('2020-12-11');
Ah interesting, let's insert this knowledge in the code. Could be my name it e.g. `vaccinationStartDateUS` or add some comments above it

2021-08-18 14:05 UTC, aikewoody commented on src/core/vaccine/VaccineApiClient.ts
> +  // Depricated as the "new" Vaccine system treats vaccine as a "Vaccination Record", and uses PATCH to "delete" doses
deprecated :)

2021-08-18 14:05 UTC, aikewoody commented on src/core/vaccine/VaccineService.ts
> +  // Depricated as the "new" Vaccine system treats vaccine as a "Vaccination Record", and uses PATCH to "delete" doses
deprecated :)

2021-08-18 14:06 UTC, aikewoody commented on src/core/vaccine/dto/VaccineRequest.ts
> +  // These are depricated fields; this data now lives on the Dose itself
deprecated :)

2021-08-18 14:08 UTC, aikewoody commented on src/features/vaccines/AboutYourVaccineScreenOld.tsx
> +        initialValues={{}}
Can this be omitted completely?

2021-08-18 14:09 UTC, aikewoody commented on src/features/vaccines/AboutYourVaccineScreenUpdated.tsx
> +          <ClickableText onPress={() => promptDelete()} style={styles.clickableText}>
Can both be shortened to `onPress={promptDelete}`

2021-08-18 14:10 UTC, aikewoody commented on src/features/vaccines/VaccineListFeatureToggleScreen.tsx
> +};
Inventive idea! 👍

2021-08-18 14:11 UTC, aikewoody commented on src/features/vaccines/VaccineListFeatureToggleScreen.tsx
> +      <VaccineListScreenOld route />
I guess this must be `route={route}`?

2021-08-18 14:12 UTC, aikewoody commented on src/features/vaccines/VaccineListFeatureToggleScreen.tsx
> +import { VaccineListScreenUpdated } from './VaccineListScreenUpdated';
Let's keep using absolute imports :)

2021-08-18 14:24 UTC, aikewoody commented on src/features/vaccines/AboutYourVaccineScreenUpdated.tsx
> +                {renderDeleteOrBack()}
Just curious about this, when do you decide to extract JSX render logic into its own function?

2021-08-18 14:26 UTC, aikewoody requested changes
Massive PR mate and great work! Overall looks good but would like to see some comments I placed resolved, besides that you have my approval 👍

2021-08-19 10:54 UTC, bionara commented on src/features/vaccines/AboutYourVaccineScreenUpdated.tsx
> +                {renderDeleteOrBack()}
Right away. Makes the render method a lot easier to read and work out the "chunks" of "logic"

2021-08-19 15:22 UTC, aikewoody approved these changes
Let's merge this baby in! (or out haha)

2021-08-19 15:25 UTC, merged