Ben/modal close
zoe/covid-tracker-react-native pull request #1570
Opened 2021-08-05 18:36 UTC by bionara

# Description

Adds a close button to the modal, and implements it for covid test onboarding.
Also added a test for the onboarding close, and tweaked the onboarding button text to be next or OK on the last item.

Waiting for Swedish word for "Next" for "button-end" and "close" for "modal-close" (couldn't match it from existing se json)

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

![image](https://user-images.githubusercontent.com/3264113/128402733-112aacdf-700b-475f-afe0-9678ae0eee05.png)
![image](https://user-images.githubusercontent.com/3264113/128402770-bdf1faab-6b4f-4da8-b9b1-c8e50ef8368b.png)

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

2021-08-05 20:04 UTC, juliatan requested changes
UI looks good Ben! I think you're missing the `await store.dispatch(fetchStartUpInfo());` dispatch action upon user hitting "close" though.

2021-08-05 20:19 UTC, bionara commented on src/features/covid-tests/modals/CovidTestListOnboardingModal.tsx
> +      showCloseButton={true}
done!

2021-08-05 20:22 UTC, bionara commented
> UI looks good Ben! I think you're missing the `await store.dispatch(fetchStartUpInfo());` dispatch action upon user hitting "close" though.

It should actually be fine as the "close function" prop handles that:
https://github.com/zoe/covid-tracker-react-native/pull/1570/files#diff-f483ed13f83c85dfd7d0487b9efbe9288e5feba94e8a53ee91011582c28713fdR82

2021-08-05 20:23 UTC, juliatan commented
> > UI looks good Ben! I think you're missing the `await store.dispatch(fetchStartUpInfo());` dispatch action upon user hitting "close" though.
> 
> It should actually be fine as the "close function" prop handles that:
> https://github.com/zoe/covid-tracker-react-native/pull/1570/files#diff-f483ed13f83c85dfd7d0487b9efbe9288e5feba94e8a53ee91011582c28713fdR82

Isn't that just a UI show/hide prop? Doesn't update backend I don't think..

2021-08-06 09:48 UTC, bionara commented
> > > UI looks good Ben! I think you're missing the `await store.dispatch(fetchStartUpInfo());` dispatch action upon user hitting "close" though.
> > 
> > 
> > It should actually be fine as the "close function" prop handles that:
> > https://github.com/zoe/covid-tracker-react-native/pull/1570/files#diff-f483ed13f83c85dfd7d0487b9efbe9288e5feba94e8a53ee91011582c28713fdR82
> 
> Isn't that just a UI show/hide prop? Doesn't update backend I don't think..

yep by design that prop from onboarding calls the close on success. In a future PR we can make it close here if needed.

2021-08-06 10:40 UTC, juliatan approved these changes
Nice refactor !

2021-08-06 10:47 UTC, selvach commented on src/features/covid-tests/modals/CovidTestListOnboardingModal.tsx
> +  async function closeAndUpateStartupInfo() {
NICE :)

2021-08-06 11:53 UTC, merged