Changed the consent screen for GB.
zoe/covid-tracker-react-native pull request #1664
Opened 2021-09-03 14:42 UTC by aikewoody

# Description

https://www.notion.so/joinzoe/New-user-signup-incorporating-reconsent-changes-4a2db938fcbf481b911b90f65a32d4bf

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Out of scope and potential follow-up

[comment]: <> (Are there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?)

## Screenshots

![Simulator Screen Shot - iPhone 8 - 2021-09-03 at 16 40 48](https://user-images.githubusercontent.com/17004429/132023853-786bcacc-fdbc-4285-958c-972ad5697e16.png)

![Simulator Screen Shot - iPhone 8 - 2021-09-03 at 16 40 51](https://user-images.githubusercontent.com/17004429/132023861-8dc84251-c5dc-44f2-b440-e01ce8e4ba1f.png)

## Checklist (for submission)

- [ ] Analytics/tracking events have been added (if relevant)
- [ ] Added new screen(s) to `src/features/screens.ts` and new Redux slice(s) to `mocks/mockedInitialState.ts` (if relevant)

## Checklist (for reviewers)

- [ ] Checked against Figma designs (if relevant)
- [ ] Checked that data has been successfully saved to the backend (if relevant)

## Checklist (for merger)

- [ ] Make sure the right merge strategy is chosen, commit merge into master and squash merge into develop.

2021-09-03 14:42 UTC, aikewoody commented
@selvach Do I need to update the version number of the UK consent?

2021-09-03 15:03 UTC, selvach commented
Check with Christina if the study consent should change?

2021-09-03 16:33 UTC, juliatan requested changes
Nice one for getting it done so quickly Aike!

Some other things: 
- I think some of the logos on the welcome screen need updating e.g. the ZOE logo should contain the registered trademark.
- On the screen with the legal cards, the title and subtitle is missing.

![Simulator Screen Shot - iPhone 11 - 2021-09-03 at 17 17 34](https://user-images.githubusercontent.com/7389546/132037992-21286be7-2cdc-4356-8760-2743a12ba4df.png)
![Simulator Screen Shot - iPhone 11 - 2021-09-03 at 17 17 40](https://user-images.githubusercontent.com/7389546/132037999-f6999387-2436-47e3-afe5-7feeb7f74070.png)

2021-09-03 16:33 UTC, juliatan commented on assets/lang/en.json
> +    "disclaimer2": "Moving forward, you may also help detect early symptoms and uncover the role of nutrition and lifestyle in other major diseases",
There should be a full stop at the end of the sentence.

2021-09-10 13:20 UTC, juliatan requested changes

2021-09-10 13:20 UTC, juliatan commented on src/features/register/Welcome2Screen.tsx
> +  }, [isGBCountry(), isSECountry(), svPartners, usPartners]);
Guess you can remove `isGBCountry()` from dependency array.

2021-09-10 13:20 UTC, juliatan submitted a review, later dismissed

2021-09-10 15:14 UTC, juliatan commented
@aikewoody Looking at Sol's latest designs, the copy has changed 😕

2021-09-13 13:22 UTC, juliatan commented
@aikewoody The first screen has also changed and needs updating for all the copy.

Also, this screen needs centre alignment. It also looks like the style of the back navigation button has changed.
![Simulator Screen Shot - iPhone 11 - 2021-09-13 at 14 20 27](https://user-images.githubusercontent.com/7389546/133090949-55cfafac-7e94-4cd9-88c0-09f53d0f8d86.png)

2021-09-13 14:36 UTC, aikewoody commented
@juliatan I have ignored the register screen as it's out of scope for the reconsent changes but you're right that in the designs this screen has changes. Will implement those as it makes the screen look better than it is now. About the back button, I want to keep that as is and create a ticket to replace all back buttons through the app to prevent having two different styles at the same time.

2021-09-13 20:53 UTC, juliatan approved these changes

2021-09-14 09:08 UTC, merged