fix: show country picker if country code is different
zoe/covid-tracker-react-native pull request #698
Opened 2020-08-18 13:23 UTC by snack-0verflow

# Description

TODO:
- Call API to update user's country code

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [x] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [x] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

Require BE work on updating user's country code.

2020-08-25 11:28 UTC, snack-0verflow commented
@abubuwe

2020-08-25 15:43 UTC, selvach commented on src/core/user/UserService.ts
> +      await AsyncStorageService.saveProfile(data);
saveProfile() has been deleted from AsyncStorageService in this PR. 
I didn't see any point in storing the response. 
https://github.com/zoe/covid-tracker-react-native/pull/708

2020-08-25 15:44 UTC, selvach commented on src/core/user/dto/UserAPIContracts.ts
> +  country_code: string;
You could make this into an Enum (GB, US, SE)

2020-08-25 16:28 UTC, snack-0verflow commented
@selvach Made some changes. Added enums & removed redundant code

2020-08-25 21:10 UTC, selvach commented on src/features/AppCoordinator.ts
> +    const profile: UserResponse | null = null;
Change line 134: from const -> let
Remove the const in line 140. Otherwise you are hiding the scope and line 144 will never evaluate as true.

2020-08-25 21:17 UTC, selvach requested changes
.

2020-08-25 21:24 UTC, snack-0verflow commented on src/features/AppCoordinator.ts
> +    const profile: UserResponse | null = null;
@selvach my bad. just pushed a commit up

2020-08-26 11:17 UTC, selvach approved these changes
Thanks for the changes! Tested locally and it looks good.

2020-08-26 11:18 UTC, merged