Update location
zoe/covid-tracker-react-native pull request #730
Opened 2020-08-24 18:10 UTC by the-kenneth

# Description

Adds in option to select different postcode and country in edit location. Adds this data along into the assessment.

2020-08-25 15:31 UTC, abubuwe reviewed
Had a playaround before the backend is wired up- overall looks great. Few comments:

- Where validation is used, let's use custom i18n messages rather than the default so this works across the nations (maybe we can re-use some of existing location errors).
- The country list is currently in a difficult to navigate order (semi-alphabetical)
- Can you add the link to the privacy policy from the "Your location" screen please?
- There is no "header" to be able to go back when you access the Edit location screen via the assessment flow. 
- The spacing on the HowYouFeel screen also looks slightly off now compared to designs.

2020-08-25 18:41 UTC, the-kenneth commented
> Had a playaround before the backend is wired up- overall looks great. Few comments:
> 
> * Where validation is used, let's use custom i18n messages rather than the default so this works across the nations (maybe we can re-use some of existing location errors).
> * The country list is currently in a difficult to navigate order (semi-alphabetical)
> * Can you add the link to the privacy policy from the "Your location" screen please?
> * There is no "header" to be able to go back when you access the Edit location screen via the assessment flow.
> * The spacing on the HowYouFeel screen also looks slightly off now compared to designs.

Did all except the link as it wasnt trivial.

2020-08-25 21:52 UTC, abubuwe requested changes

2020-08-25 21:52 UTC, abubuwe commented on src/features/multi-profile/edit-profile/EditLocationScreen.tsx
> +      infos.current_country_code = '';
@selvach @snack-0verflow to confirm but I believe these need to be sending `null` to the backend, since the backend coercion checks using a non-null check and therefore this would break that.

2020-08-25 21:52 UTC, abubuwe commented on src/features/multi-profile/edit-profile/EditLocationScreen.tsx
> +        infos.current_country_code = '';
same as above

2020-08-25 21:52 UTC, abubuwe commented on src/features/multi-profile/edit-profile/EditLocationScreen.tsx
> +        infos.current_postcode = '';
same as above

2020-08-25 21:54 UTC, abubuwe commented on src/features/multi-profile/edit-profile/EditLocationScreen.tsx
> +        })}
perhaps move the schema out into it's own constant (like in other examples/with initalFormValues) for readability of code.

2020-08-25 22:00 UTC, abubuwe commented on src/features/assessment/HowYouFeelScreen.tsx
> +              <RegularText>{i18n.t('how-you-feel.current-location') + ' ' + location}</RegularText>
can we bold the postcode please?

2020-08-26 10:03 UTC, abubuwe commented on src/features/multi-profile/edit-profile/EditLocationScreen.tsx
> +      infos.current_country_code = '';
@snack-0verflow

2020-08-26 11:43 UTC, snack-0verflow approved these changes

2020-08-26 13:03 UTC, abubuwe submitted a review, later dismissed

2020-08-26 13:06 UTC, abubuwe commented on src/features/assessment/HowYouFeelScreen.tsx
> +                  {location.length !== 2 ? location : getName(location)}
When might we expect location to not be 2 char code?

2020-08-26 13:54 UTC, the-kenneth commented on src/features/assessment/HowYouFeelScreen.tsx
> +                  {location.length !== 2 ? location : getName(location)}
Its either a country code or a postcode. However ive now moved it higher for clarity.

2020-08-26 14:08 UTC, abubuwe approved these changes

2020-08-26 14:14 UTC, merged