Features/trendline
zoe/covid-tracker-react-native pull request #814
Opened 2020-10-06 15:43 UTC by snack-0verflow

# Description

_Description of the feature or fix with link to the issue if existing_

## On what platform have you tested the change?

- [ ] Android - Emulator
- [ ] Android - Physical device
- [ ] iOS - Emulator
- [ ] iOS - Physical device

## Screenshots

_Please attach screenshots showing the change if relevant_

## Checklist

- [ ] I have updated mockServer
- [ ] I've added analytics as relevent
- [ ] I have run `npm test`
- [ ] I have run `npm run test:i18n`

## Out of scope and potential follow-up

_Is there any related changes that you plan to do in a follow-up PR or voluntarily excluded from the scope?_

2020-10-07 13:15 UTC, the-kenneth requested changes

2020-10-07 13:29 UTC, the-kenneth commented on src/components/Nav/Tabs.tsx
> +            style={[
Doesnt need to be an array for 1 object

2020-10-07 13:41 UTC, the-kenneth commented on src/features/dashboard/DashboardScreen.tsx
> +  console.log(localTrendline);
Remove log

2020-10-07 13:54 UTC, the-kenneth commented on src/components/Nav/Tabs.tsx
> +            ]}>
This also doesn't need to be in an array.

2020-10-08 07:32 UTC, snack-0verflow commented on src/components/Nav/Tabs.tsx
> +            ]}>
@the-kenneth the array is needed for transform style.

2020-10-08 10:43 UTC, the-kenneth commented on assets/charts/trendline-overview.html
> +    //   });
Do we need to keep this?

2020-10-08 14:55 UTC, snack-0verflow commented on assets/charts/trendline-overview.html
> +    //   });
no sir we dont

2020-10-08 20:01 UTC, the-kenneth approved these changes

2020-10-13 13:02 UTC, the-kenneth approved these changes

2020-10-13 13:02 UTC, merged